// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package store

import (
	"context"
)

const addCharacterFact = `-- name: AddCharacterFact :exec
INSERT INTO character_facts (id, character_id, name, value, type)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type AddCharacterFactParams struct {
	ID          string
	CharacterID *string
	Name        *string
	Value       *string
	Type        *string
}

func (q *Queries) AddCharacterFact(ctx context.Context, arg AddCharacterFactParams) error {
	_, err := q.db.ExecContext(ctx, addCharacterFact,
		arg.ID,
		arg.CharacterID,
		arg.Name,
		arg.Value,
		arg.Type,
	)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, name, base_prompt, description, updated_at, created_at
FROM characters
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetCharacter(ctx context.Context, id string) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BasePrompt,
		&i.Description,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterFacts = `-- name: GetCharacterFacts :many
SELECT id, character_id, name, value, type, created_at, updated_at
FROM character_facts
WHERE character_id = ?1
ORDER BY updated_at DESC
LIMIT ?2
`

type GetCharacterFactsParams struct {
	CharacterID *string
	Limit       int64
}

func (q *Queries) GetCharacterFacts(ctx context.Context, arg GetCharacterFactsParams) ([]CharacterFact, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterFacts, arg.CharacterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterFact
	for rows.Next() {
		var i CharacterFact
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.Value,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacters = `-- name: GetCharacters :many
SELECT id, name, base_prompt, description, updated_at, created_at
FROM characters
`

func (q *Queries) GetCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BasePrompt,
			&i.Description,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
