// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package store

import (
	"context"
	"time"
)

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (id, max_window_size, character_id, user_id)
VALUES (?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID            string
	MaxWindowSize *int64
	CharacterID   *string
	UserID        *string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.MaxWindowSize,
		arg.CharacterID,
		arg.UserID,
	)
	return err
}

const createConversationMessage = `-- name: CreateConversationMessage :exec
INSERT INTO conversation_messages (id, conversation_id, content, role, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateConversationMessageParams struct {
	ID             string
	ConversationID *string
	Content        []byte
	Role           *string
	CreatedAt      *time.Time
}

func (q *Queries) CreateConversationMessage(ctx context.Context, arg CreateConversationMessageParams) error {
	_, err := q.db.ExecContext(ctx, createConversationMessage,
		arg.ID,
		arg.ConversationID,
		arg.Content,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, max_window_size, character_id, user_id, current_summary, created_at, updated_at
FROM conversations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MaxWindowSize,
		&i.CharacterID,
		&i.UserID,
		&i.CurrentSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationWindowSize = `-- name: GetConversationWindowSize :one
SELECT max_window_size
FROM conversations
WHERE id = ?
`

func (q *Queries) GetConversationWindowSize(ctx context.Context, id string) (*int64, error) {
	row := q.db.QueryRowContext(ctx, getConversationWindowSize, id)
	var max_window_size *int64
	err := row.Scan(&max_window_size)
	return max_window_size, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, conversation_id, role, content, created_at
FROM conversation_messages
WHERE conversation_id = ?
`

func (q *Queries) ListConversationMessages(ctx context.Context, conversationID *string) ([]ConversationMessage, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMessage
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, conversation_id, role, content, created_at
FROM conversation_messages
WHERE conversation_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRecentMessagesParams struct {
	ConversationID *string
	Limit          int64
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ConversationMessage, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMessage
	for rows.Next() {
		var i ConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
