// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package store

import (
	"context"
	"strings"
)

const createMemory = `-- name: CreateMemory :exec
INSERT INTO memories (
  id, user_id, character_id, content, embedding, importance, confidence, source, tags
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateMemoryParams struct {
	ID          string
	UserID      *string
	CharacterID *string
	Content     *string
	Embedding   []byte
	Importance  *float64
	Confidence  *float64
	Source      *string
	Tags        *string
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) error {
	_, err := q.db.ExecContext(ctx, createMemory,
		arg.ID,
		arg.UserID,
		arg.CharacterID,
		arg.Content,
		arg.Embedding,
		arg.Importance,
		arg.Confidence,
		arg.Source,
		arg.Tags,
	)
	return err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories
WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMemory, id)
	return err
}

const getAllEmbeddings = `-- name: GetAllEmbeddings :many
SELECT id, embedding
FROM memories
`

type GetAllEmbeddingsRow struct {
	ID        string
	Embedding []byte
}

func (q *Queries) GetAllEmbeddings(ctx context.Context) ([]GetAllEmbeddingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEmbeddings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEmbeddingsRow
	for rows.Next() {
		var i GetAllEmbeddingsRow
		if err := rows.Scan(&i.ID, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoriesByIDs = `-- name: GetMemoriesByIDs :many
SELECT id, user_id, character_id, content, embedding, importance, confidence, source, tags, access_count, decay_score, last_accessed_at, created_at, updated_at
FROM memories
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetMemoriesByIDs(ctx context.Context, ids []string) ([]Memory, error) {
	query := getMemoriesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CharacterID,
			&i.Content,
			&i.Embedding,
			&i.Importance,
			&i.Confidence,
			&i.Source,
			&i.Tags,
			&i.AccessCount,
			&i.DecayScore,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
