// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"
)

type Character struct {
	ID          string
	Name        *string
	BasePrompt  *string
	Description *string
	UpdatedAt   *time.Time
	CreatedAt   *time.Time
}

type CharacterFact struct {
	ID          string
	CharacterID *string
	Name        *string
	Value       *string
	Type        *string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

type Conversation struct {
	ID             string
	Title          *string
	MaxWindowSize  *int64
	CharacterID    *string
	UserID         *string
	CurrentSummary *string
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
}

type ConversationMessage struct {
	ID             string
	ConversationID *string
	Role           *string
	Content        []byte
	CreatedAt      *time.Time
}

type Memory struct {
	ID             string
	UserID         *string
	CharacterID    *string
	Content        *string
	Embedding      []byte
	Importance     *float64
	Confidence     *float64
	Source         *string
	Tags           *string
	AccessCount    *int64
	DecayScore     *float64
	LastAccessedAt *time.Time
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
}

type User struct {
	ID        string
	Name      *string
	Bio       *string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

type UserFact struct {
	ID        string
	Name      *string
	Value     *string
	Type      *string
	UserID    *string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}
