// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package store

import (
	"context"
)

const addUserFact = `-- name: AddUserFact :exec
INSERT INTO user_facts (id, user_id, name, value, type)
VALUES (?, ?, ?, ?, ?)
`

type AddUserFactParams struct {
	ID     string
	UserID *string
	Name   *string
	Value  *string
	Type   *string
}

func (q *Queries) AddUserFact(ctx context.Context, arg AddUserFactParams) error {
	_, err := q.db.ExecContext(ctx, addUserFact,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Value,
		arg.Type,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, bio, created_at, updated_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFacts = `-- name: GetUserFacts :many
SELECT id, name, value, type, user_id, created_at, updated_at
FROM user_facts
WHERE user_id = ?
ORDER BY updated_at DESC
LIMIT ?
`

type GetUserFactsParams struct {
	UserID *string
	Limit  int64
}

func (q *Queries) GetUserFacts(ctx context.Context, arg GetUserFactsParams) ([]UserFact, error) {
	rows, err := q.db.QueryContext(ctx, getUserFacts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFact
	for rows.Next() {
		var i UserFact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Type,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
